# Generated by Django 5.2.16 on 2026-07-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity',
            field=models.CharField(choices=[('under_three', 'under_three'), ('three', 'three'), ('more_three', 'more_three')], default='physical_health', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_day',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='daily_calorie_goal',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('m', 'M'), ('f', 'F')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='start_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='goal',
            field=models.CharField(choices=[('weight_loss', 'weight_loss'), ('muscle_gain', 'muscle_gain'), ('physical_health', 'physical_health')], max_length=20),
        ),
    ]
