# Generated by Django 5.2.16 on 2026-07-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_activity_user_birth_day_user_daily_calorie_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='total_carbs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='total_fats',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='total_protein',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='daily_carbs_goal',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='daily_fats_goal',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='daily_protein_goal',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='activity',
            field=models.CharField(choices=[('under_three', 'under_three'), ('three', 'three'), ('more_three', 'more_three')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='goal',
            field=models.CharField(choices=[('weight_loss', 'weight_loss'), ('muscle_gain', 'muscle_gain'), ('physical_health', 'physical_health')], default='physical_health', max_length=20),
        ),
    ]
