# Generated by Django 5.2.16 on 2026-07-29 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_meal_total_carbs_meal_total_fats_meal_total_protein_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='daily_calorie_goal',
            new_name='daily_calories_goal',
        ),
    ]
