# Generated by Django 5.2.16 on 2026-07-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_daily_calorie_goal_user_daily_calories_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('grains', 'Grains'), ('meat', 'Meat & Fish'), ('dairy', 'Dairy'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('dishes', 'Dishes'), ('drinks', 'Drinks'), ('snacks', 'Snacks'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
