# Generated by Django 5.2.16 on 2026-08-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_is_custom_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttype',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
